// =============================================
// ARQUIVO: src/js/communication/caaData.js
// DESCRIÇÃO: Dados do CAA (Comunicação Aumentativa e Alternativa)
// =============================================

const CaaData = {
  // Menu Principal
  root: [
    {
      id: "root_sim",
      label: "Sim",
      icon: "👍",
      speech: "Sim",
      colorClass: "bg-green-100 border-green-300 text-green-800",
      action: "speak",
    },
    {
      id: "root_nao",
      label: "Não",
      icon: "👎",
      speech: "Não",
      colorClass: "bg-red-100 border-red-300 text-red-800",
      action: "speak",
    },
    {
      id: "root_ajuda",
      label: "Ajuda",
      icon: "❓",
      speech: "Ajuda",
      colorClass: "bg-yellow-100 border-yellow-300 text-yellow-800",
      action: "speak",
    },
    {
      id: "root_quero",
      label: "Eu Quero",
      icon: "✋",
      speech: "Eu quero",
      colorClass: "bg-blue-100 border-blue-300 text-blue-800",
      action: "navigate",
      targetCategory: "quero_items",
    },
    {
      id: "root_nao_quero",
      label: "Não Quero",
      icon: "✊",
      speech: "Eu não quero",
      colorClass: "bg-red-200 border-red-400 text-red-900",
      action: "navigate",
      targetCategory: "nao_quero_items",
    },
    {
      id: "root_estou",
      label: "Eu Estou",
      icon: "🙂",
      speech: "Eu estou",
      colorClass: "bg-purple-100 border-purple-300 text-purple-800",
      action: "navigate",
      targetCategory: "estou_items",
    },
  ],

  // Subcategorias
  categories: {
    // --- MENU "EU QUERO" ---
    quero_items: [
      // 1. PRIORIDADE ALTA=
      {
        id: "act_dormir",
        label: "Dormir",
        icon: "😴",
        speechSuffix: "dormir",
        colorClass: "bg-white border-blue-300 shadow-sm",
      },
      {
        id: "act_banheiro",
        label: "Banheiro",
        icon: "🚽",
        speechSuffix: "ir ao banheiro",
        colorClass: "bg-white border-blue-300 shadow-sm",
      },
      {
        id: "act_casa",
        label: "Casa",
        icon: "🏠",
        speechSuffix: "ir para casa",
        colorClass: "bg-white border-blue-300 shadow-sm",
      },
      {
        id: "act_comer",
        label: "Comer",
        icon: "🍽️",
        speechSuffix: "comer",
        colorClass: "bg-white border-blue-300 shadow-sm",
      },

      // 2. PASTAS (Categorias)
      {
        id: "cat_brinquedos",
        label: "Brinquedos",
        icon: "🧸",
        action: "navigate",
        targetCategory: "brinquedos_items",
        colorClass: "bg-teal-50 border-teal-200",
      },
      {
        id: "cat_comidas",
        label: "Comidas",
        icon: "🥘",
        action: "navigate",
        targetCategory: "comidas_items",
        colorClass: "bg-orange-50 border-orange-200",
      },
      {
        id: "cat_bebidas",
        label: "Bebidas",
        icon: "🥤",
        action: "navigate",
        targetCategory: "bebidas_items",
        colorClass: "bg-blue-50 border-blue-200",
      },
      {
        id: "cat_frutas",
        label: "Frutas",
        icon: "🍎",
        action: "navigate",
        targetCategory: "frutas_items",
        colorClass: "bg-green-50 border-green-200",
      },
      {
        id: "cat_legumes",
        label: "Legumes",
        icon: "🥕",
        action: "navigate",
        targetCategory: "legumes_items",
        colorClass: "bg-green-50 border-green-200",
      },
      {
        id: "cat_cafe",
        label: "Café Manhã",
        icon: "🥐",
        action: "navigate",
        targetCategory: "cafe_items",
        colorClass: "bg-yellow-50 border-yellow-200",
      },
      {
        id: "cat_diversos",
        label: "Lanches",
        icon: "🍩",
        action: "navigate",
        targetCategory: "diversos_items",
        colorClass: "bg-pink-50 border-pink-200",
      },

      {
        id: "cat_cuidados",
        label: "Cuidados",
        icon: "🧼",
        action: "navigate",
        targetCategory: "cuidados_items",
        colorClass: "bg-cyan-50 border-cyan-200",
      },
      {
        id: "cat_passeios",
        label: "Passeios",
        icon: "🎡",
        action: "navigate",
        targetCategory: "passeios_items",
        colorClass: "bg-indigo-50 border-indigo-200",
      },
      {
        id: "cat_escola",
        label: "Escola",
        icon: "🎒",
        action: "navigate",
        targetCategory: "escola_items",
        colorClass: "bg-yellow-50 border-yellow-300",
      },
      {
        id: "cat_acoes",
        label: "Ações",
        icon: "🏃",
        action: "navigate",
        targetCategory: "acoes_items",
        colorClass: "bg-gray-50 border-gray-300",
      },
    ],

    // --- MENU "EU NÃO QUERO" ---
    nao_quero_items: [
      // Mesma lógica de prioridade, mas com borda vermelha
      {
        id: "act_dormir_nq",
        label: "Dormir",
        icon: "😴",
        speechSuffix: "dormir",
        colorClass: "bg-white border-red-300",
      },
      {
        id: "act_banheiro_nq",
        label: "Banheiro",
        icon: "🚽",
        speechSuffix: "ir ao banheiro",
        colorClass: "bg-white border-red-300",
      },
      {
        id: "act_casa_nq",
        label: "Casa",
        icon: "🏠",
        speechSuffix: "ir para casa",
        colorClass: "bg-white border-red-300",
      },
      {
        id: "act_comer_nq",
        label: "Comer",
        icon: "🍽️",
        speechSuffix: "comer",
        colorClass: "bg-white border-red-300",
      },

      // Pastas
      {
        id: "cat_brinquedos_nq",
        label: "Brinquedos",
        icon: "🧸",
        action: "navigate",
        targetCategory: "brinquedos_items",
        colorClass: "bg-teal-50 border-teal-200",
      },
      {
        id: "cat_comidas_nq",
        label: "Comidas",
        icon: "🥘",
        action: "navigate",
        targetCategory: "comidas_items",
        colorClass: "bg-orange-50 border-orange-200",
      },
      {
        id: "cat_bebidas_nq",
        label: "Bebidas",
        icon: "🥤",
        action: "navigate",
        targetCategory: "bebidas_items",
        colorClass: "bg-blue-50 border-blue-200",
      },
      {
        id: "cat_frutas_nq",
        label: "Frutas",
        icon: "🍎",
        action: "navigate",
        targetCategory: "frutas_items",
        colorClass: "bg-green-50 border-green-200",
      },
      {
        id: "cat_legumes_nq",
        label: "Legumes",
        icon: "🥕",
        action: "navigate",
        targetCategory: "legumes_items",
        colorClass: "bg-green-50 border-green-200",
      },
      {
        id: "cat_cafe_nq",
        label: "Café Manhã",
        icon: "🥐",
        action: "navigate",
        targetCategory: "cafe_items",
        colorClass: "bg-yellow-50 border-yellow-200",
      },
      {
        id: "cat_diversos_nq",
        label: "Lanches",
        icon: "🍩",
        action: "navigate",
        targetCategory: "diversos_items",
        colorClass: "bg-pink-50 border-pink-200",
      },
      {
        id: "cat_cuidados_nq",
        label: "Cuidados",
        icon: "🧼",
        action: "navigate",
        targetCategory: "cuidados_items",
        colorClass: "bg-cyan-50 border-cyan-200",
      },
      {
        id: "cat_escola_nq",
        label: "Escola",
        icon: "🎒",
        action: "navigate",
        targetCategory: "escola_items",
        colorClass: "bg-yellow-50 border-yellow-300",
      },
    ],

    // ----------------------------------
    // CATEGORIAS DETALHADAS
    // ----------------------------------

    // 1. BRINQUEDOS
    brinquedos_items: [
      {
        id: "toy_brincar_gen",
        label: "Brincar",
        icon: "🤹",
        speechSuffix: "brincar",
        colorClass: "bg-white border-teal-300 shadow-sm",
      },

      {
        id: "toy_bola",
        label: "Bola",
        icon: "⚽",
        speechSuffix: "bola",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_carro",
        label: "Carrinho",
        icon: "🚗",
        speechSuffix: "carrinho",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_boneca",
        label: "Boneca(o)",
        icon: "🎎",
        speechSuffix: "boneca",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_blocos",
        label: "Blocos",
        icon: "🧱",
        speechSuffix: "brincar de blocos",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_puzzle",
        label: "Quebra-Cabeça",
        icon: "🧩",
        speechSuffix: "quebra cabeça",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_massinha",
        label: "Massinha",
        icon: "🟣",
        speechSuffix: "massinha",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_tablet",
        label: "Tablet",
        icon: "📱",
        speechSuffix: "tablet",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_bolha",
        label: "Bolha de Sabão",
        icon: "🫧",
        speechSuffix: "bolha de sabão",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_desenhar",
        label: "Desenhar",
        icon: "🖍️",
        speechSuffix: "desenhar",
        colorClass: "bg-white border-teal-200",
      },
      {
        id: "toy_urso",
        label: "Ursinho",
        icon: "🧸",
        speechSuffix: "ursinho",
        colorClass: "bg-white border-teal-200",
      },
    ],

    // 2. CUIDADOS PESSOAIS
    cuidados_items: [
      {
        id: "care_banho",
        label: "Tomar Banho",
        icon: "🚿",
        speechSuffix: "tomar banho",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_dentes",
        label: "Escovar Dentes",
        icon: "🪥",
        speechSuffix: "escovar os dentes",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_maos",
        label: "Lavar Mãos",
        icon: "👏",
        speechSuffix: "lavar as mãos",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_xixi",
        label: "Xixi",
        icon: "🚽",
        speechSuffix: "fazer xixi",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_coco",
        label: "Cocô",
        icon: "💩",
        speechSuffix: "fazer cocô",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_pente",
        label: "Pentear Cabelo",
        icon: "💇",
        speechSuffix: "pentear o cabelo",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_roupa",
        label: "Trocar Roupa",
        icon: "👕",
        speechSuffix: "trocar de roupa",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_cortar_unha",
        label: "Cortar Unha",
        icon: "💅",
        speechSuffix: "cortar a unha",
        colorClass: "bg-white border-cyan-200",
      },
      {
        id: "care_remedio",
        label: "Remédio",
        icon: "💊",
        speechSuffix: "tomar remédio",
        colorClass: "bg-white border-cyan-200",
      },
    ],

    // 3. PASSEIOS
    passeios_items: [
      {
        id: "place_parque",
        label: "Parque",
        icon: "🛝",
        speechSuffix: "ir ao parque",
        colorClass: "bg-white border-indigo-200",
      },
      {
        id: "place_casa_vovo",
        label: "Casa da Vovó",
        icon: "👵",
        speechSuffix: "ir na casa da vovó",
        colorClass: "bg-white border-indigo-200",
      },
      {
        id: "place_shopping",
        label: "Shopping",
        icon: "🛍️",
        speechSuffix: "ir ao shopping",
        colorClass: "bg-white border-indigo-200",
      },
      {
        id: "place_piscina",
        label: "Piscina",
        icon: "🏊",
        speechSuffix: "ir na piscina",
        colorClass: "bg-white border-indigo-200",
      },
      {
        id: "place_praia",
        label: "Praia",
        icon: "🏖️",
        speechSuffix: "ir à praia",
        colorClass: "bg-white border-indigo-200",
      },
      {
        id: "place_carro",
        label: "Passear de Carro",
        icon: "🚗",
        speechSuffix: "passear de carro",
        colorClass: "bg-white border-indigo-200",
      },
      {
        id: "place_supermercado",
        label: "Supermercado",
        icon: "🛒",
        speechSuffix: "ir ao mercado",
        colorClass: "bg-white border-indigo-200",
      },
    ],

    // 4. ESCOLA
    escola_items: [
      {
        id: "sch_escola",
        label: "Escola",
        icon: "🏫",
        speechSuffix: "ir para a escola",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "sch_mochila",
        label: "Mochila",
        icon: "🎒",
        speechSuffix: "minha mochila",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "sch_tarefa",
        label: "Dever de Casa",
        icon: "📝",
        speechSuffix: "fazer dever de casa",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "sch_pintar",
        label: "Pintar",
        icon: "🎨",
        speechSuffix: "pintar",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "sch_colar",
        label: "Colar",
        icon: "🧴",
        speechSuffix: "colar",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "sch_recortar",
        label: "Recortar",
        icon: "✂️",
        speechSuffix: "recortar",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "sch_terapia",
        label: "Terapia",
        icon: "🗣️",
        speechSuffix: "ir na terapia",
        colorClass: "bg-white border-yellow-200",
      },
    ],

    // 5. AÇÕES
    acoes_items: [
      {
        id: "act_ver",
        label: "Ver",
        icon: "👀",
        speechSuffix: "ver",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_tocar",
        label: "Tocar",
        icon: "👆",
        speechSuffix: "tocar",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_ouvir",
        label: "Ouvir",
        icon: "👂",
        speechSuffix: "ouvir",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_desenhar",
        label: "Desenhar",
        icon: "✏️",
        speechSuffix: "desenhar",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_ler",
        label: "Ler",
        icon: "📖",
        speechSuffix: "ler",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_correr",
        label: "Correr",
        icon: "🏃",
        speechSuffix: "correr",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_beber",
        label: "Beber",
        icon: "🥤",
        speechSuffix: "beber",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_esperar",
        label: "Esperar",
        icon: "⌛",
        speechSuffix: "esperar",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_parar",
        label: "Parar",
        icon: "🛑",
        speechSuffix: "parar",
        colorClass: "bg-white border-gray-200",
      },
      {
        id: "act_tomar_banho",
        label: "Tomar Banho",
        icon: "🛀",
        speechSuffix: "tomar banho",
        colorClass: "bg-white border-gray-200",
      },
    ],

    // 6. CAFÉ DA MANHÃ
    cafe_items: [
      {
        id: "food_ovo",
        label: "Ovo",
        icon: "🥚",
        speechSuffix: "ovo",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "food_manteiga",
        label: "Manteiga",
        icon: "🧈",
        speechSuffix: "manteiga",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "food_pao",
        label: "Pão",
        icon: "🍞",
        speechSuffix: "pão",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "food_queijo",
        label: "Queijo",
        icon: "🧀",
        speechSuffix: "queijo",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "food_sanduiche",
        label: "Sanduíche",
        icon: "🥪",
        speechSuffix: "sanduíche",
        colorClass: "bg-white border-yellow-200",
      },
      {
        id: "food_panquecas",
        label: "Panquecas",
        icon: "🥞",
        speechSuffix: "panquecas",
        colorClass: "bg-white border-yellow-200",
      },
    ],

    // 7. COMIDAS
    comidas_items: [
      {
        id: "food_arroz",
        label: "Arroz",
        icon: "🍚",
        speechSuffix: "arroz",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_feijao",
        label: "Feijão",
        icon: "🫘",
        speechSuffix: "feijão",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_carne",
        label: "Carne",
        icon: "🥩",
        speechSuffix: "carne",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_bacon",
        label: "Bacon",
        icon: "🥓",
        speechSuffix: "bacon",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_frango",
        label: "Frango",
        icon: "🍗",
        speechSuffix: "frango",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_peixe",
        label: "Peixe",
        icon: "🐟",
        speechSuffix: "peixe",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_camarao",
        label: "Camarão",
        icon: "🦐",
        speechSuffix: "camarão",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_hamburguer",
        label: "Hambúrguer",
        icon: "🍔",
        speechSuffix: "hambúrguer",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_salsicha",
        label: "Salsicha",
        icon: "🌭",
        speechSuffix: "salsicha",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "food_frutos_mar",
        label: "Frutos do Mar",
        icon: "🦞",
        speechSuffix: "frutos do mar",
        colorClass: "bg-white border-orange-200",
      },
    ],

    // 8. BEBIDAS
    bebidas_items: [
      {
        id: "drink_leite",
        label: "Leite",
        icon: "🥛",
        speechSuffix: "leite",
        colorClass: "bg-white border-blue-200",
      },
      {
        id: "drink_milkshake",
        label: "Milkshake",
        icon: "🥤",
        speechSuffix: "milkshake",
        colorClass: "bg-white border-blue-200",
      },
      {
        id: "drink_coco",
        label: "Água de Coco",
        icon: "🥥",
        speechSuffix: "água de coco",
        colorClass: "bg-white border-blue-200",
      },
      {
        id: "drink_agua",
        label: "Água",
        icon: "💧",
        speechSuffix: "água",
        colorClass: "bg-white border-blue-200",
      },
      {
        id: "drink_suco",
        label: "Suco",
        icon: "🧃",
        speechSuffix: "suco",
        colorClass: "bg-white border-blue-200",
      },
    ],

    // 9. DIVERSOS
    diversos_items: [
      {
        id: "snack_sopa",
        label: "Sopa",
        icon: "🍲",
        speechSuffix: "sopa",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_espaguete",
        label: "Espaguete",
        icon: "🍝",
        speechSuffix: "espaguete",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_pizza",
        label: "Pizza",
        icon: "🍕",
        speechSuffix: "pizza",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_pipoca",
        label: "Pipoca",
        icon: "🍿",
        speechSuffix: "pipoca",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_sorvete",
        label: "Sorvete",
        icon: "🍨",
        speechSuffix: "sorvete",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_donut",
        label: "Donut",
        icon: "🍩",
        speechSuffix: "donut",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_biscoito",
        label: "Biscoito",
        icon: "🍪",
        speechSuffix: "biscoito",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_bolo",
        label: "Bolo",
        icon: "🍰",
        speechSuffix: "bolo",
        colorClass: "bg-white border-pink-200",
      },
      {
        id: "snack_chocolate",
        label: "Chocolate",
        icon: "🍫",
        speechSuffix: "chocolate",
        colorClass: "bg-white border-pink-200",
      },
    ],

    // 10. FRUTAS
    frutas_items: [
      {
        id: "fruit_maca",
        label: "Maçã",
        icon: "🍎",
        speechSuffix: "maçã",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_banana",
        label: "Banana",
        icon: "🍌",
        speechSuffix: "banana",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_laranja",
        label: "Laranja",
        icon: "🍊",
        speechSuffix: "laranja",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_melancia",
        label: "Melancia",
        icon: "🍉",
        speechSuffix: "melancia",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_uva",
        label: "Uva",
        icon: "🍇",
        speechSuffix: "uva",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_morango",
        label: "Morango",
        icon: "🍓",
        speechSuffix: "morango",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_abacaxi",
        label: "Abacaxi",
        icon: "🍍",
        speechSuffix: "abacaxi",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_manga",
        label: "Manga",
        icon: "🥭",
        speechSuffix: "manga",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_pessego",
        label: "Pêssego",
        icon: "🍑",
        speechSuffix: "pêssego",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_pera",
        label: "Pera",
        icon: "🍐",
        speechSuffix: "pera",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_limao",
        label: "Limão",
        icon: "🍋",
        speechSuffix: "limão",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_cereja",
        label: "Cereja",
        icon: "🍒",
        speechSuffix: "cereja",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_kiwi",
        label: "Kiwi",
        icon: "🥝",
        speechSuffix: "kiwi",
        colorClass: "bg-white border-green-200",
      },
      {
        id: "fruit_melao",
        label: "Melão",
        icon: "🍈",
        speechSuffix: "melão",
        colorClass: "bg-white border-green-200",
      },
    ],

    // 11. LEGUMES
    legumes_items: [
      {
        id: "veg_cenoura",
        label: "Cenoura",
        icon: "🥕",
        speechSuffix: "cenoura",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_brocolis",
        label: "Brócolis",
        icon: "🥦",
        speechSuffix: "brócolis",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_alface",
        label: "Alface",
        icon: "🥬",
        speechSuffix: "alface",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_berinjela",
        label: "Berinjela",
        icon: "🍆",
        speechSuffix: "berinjela",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_milho",
        label: "Milho",
        icon: "🌽",
        speechSuffix: "milho",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_batata",
        label: "Batata",
        icon: "🥔",
        speechSuffix: "batata",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_batata_doce",
        label: "Batata-doce",
        icon: "🍠",
        speechSuffix: "batata doce",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_pepino",
        label: "Pepino",
        icon: "🥒",
        speechSuffix: "pepino",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_pimentao",
        label: "Pimentão",
        icon: "🫑",
        speechSuffix: "pimentão",
        colorClass: "bg-white border-orange-200",
      },
      {
        id: "veg_salada",
        label: "Salada",
        icon: "🥗",
        speechSuffix: "salada",
        colorClass: "bg-white border-orange-200",
      },
    ],

    // 12. SENTIMENTOS
    estou_items: [
      {
        id: "emo_feliz",
        label: "Feliz",
        icon: "😀",
        speechSuffix: "feliz",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_contente",
        label: "Contente",
        icon: "😄",
        speechSuffix: "contente",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_triste",
        label: "Triste",
        icon: "🥺",
        speechSuffix: "triste",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_surpreso",
        label: "Surpreso",
        icon: "😮",
        speechSuffix: "surpreso",
        colorClass: "bg-white border-purple-200",
      },
      // NOVO ITEM: Com Sede
      {
        id: "emo_sede",
        label: "Com Sede",
        icon: "🥤",
        speechSuffix: "com sede",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_calor",
        label: "Com Calor",
        icon: "🥵",
        speechSuffix: "com calor",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_frio",
        label: "Com Frio",
        icon: "🥶",
        speechSuffix: "com frio",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_assustado",
        label: "Assustado",
        icon: "😱",
        speechSuffix: "assustado",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_medo",
        label: "Com Medo",
        icon: "😨",
        speechSuffix: "com medo",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_raiva",
        label: "Com Raiva",
        icon: "😠",
        speechSuffix: "com raiva",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_enjoado",
        label: "Enjoado",
        icon: "🤢",
        speechSuffix: "enjoado",
        colorClass: "bg-white border-purple-200",
      },
      {
        id: "emo_cansado",
        label: "Cansado",
        icon: "😴",
        speechSuffix: "cansado",
        colorClass: "bg-white border-purple-200",
      },
    ],
  },
};
