// =============================================
// ARQUIVO: src/js/games/guess_sound/soundData.js
// DESCRIÇÃO: Dados estáticos dos Mundos e Itens da Jornada
// =============================================

const SoundJourneyData = [
  {
    id: "wild_life",
    title: "Floresta Selvagem",
    color: "green", 
    bgGradient: "from-green-100 to-green-200",
    icon: "🦁",
    items: [
      { emoji: "🐗", name: "Javali", speech: "Javali" },
      { emoji: "🦓", name: "Zebra", speech: "Zebra" },
      { emoji: "🐻", name: "Urso", speech: "Urso" },
      { emoji: "🐨", name: "Coala", speech: "Coala" },
      { emoji: "🐻‍❄️", name: "Urso Polar", speech: "Urso Polar" },
      { emoji: "🐒", name: "Macaco", speech: "Macaco" },
      { emoji: "🐆", name: "Leopardo", speech: "Leopardo" },
      { emoji: "🐅", name: "Tigre", speech: "Tigre" },
      { emoji: "🦍", name: "Gorila", speech: "Gorila" },
      { emoji: "🦛", name: "Hipopótamo", speech: "Hipopótamo" },
      { emoji: "🦏", name: "Rinoceronte", speech: "Rinoceronte" },
      { emoji: "🦔", name: "Ouriço", speech: "Ouriço" },
      { emoji: "🦥", name: "Preguiça", speech: "Preguiça" },
      { emoji: "🦘", name: "Canguru", speech: "Canguru" },
      { emoji: "🐘", name: "Elefante", speech: "Elefante" },
      { emoji: "🦁", name: "Leão", speech: "Leão" },
      { emoji: "🦊", name: "Raposa", speech: "Raposa" },
    ],
  },
  {
    id: "farm",
    title: "Fazenda Feliz",
    color: "yellow", // var(--game-yellow)
    bgGradient: "from-yellow-100 to-orange-100",
    icon: "🚜",
    items: [
      { emoji: "🐶", name: "Cachorro", speech: "Cachorro" },
      { emoji: "🐮", name: "Vaca", speech: "Vaca" },
      { emoji: "🐷", name: "Porco", speech: "Porco" },
      { emoji: "🐸", name: "Sapo", speech: "Sapo" },
      { emoji: "🐔", name: "Galinha", speech: "Galinha" },
      { emoji: "🐕", name: "Cão Pastor", speech: "Cão Pastor" },
      { emoji: "🐈", name: "Gato", speech: "Gato" },
      { emoji: "🐖", name: "Leitão", speech: "Leitão" },
      { emoji: "🐿️", name: "Esquilo", speech: "Esquilo" },
      { emoji: "🐇", name: "Coelho", speech: "Coelho" },
      { emoji: "🦆", name: "Pato", speech: "Pato" },
      { emoji: "🦃", name: "Peru", speech: "Peru" },
      { emoji: "🐤", name: "Pintinho", speech: "Pintinho" },
    ],
  },
  {
    id: "aquatic",
    title: "Mundo Aquático",
    color: "blue", // var(--game-blue)
    bgGradient: "from-blue-100 to-cyan-200",
    icon: "🐬",
    items: [
      { emoji: "🦈", name: "Tubarão", speech: "Tubarão" },
      { emoji: "🐬", name: "Golfinho", speech: "Golfinho" },
      { emoji: "🦭", name: "Foca", speech: "Foca" },
      { emoji: "🐳", name: "Baleia", speech: "Baleia" },
      { emoji: "🐋", name: "Orca", speech: "Orca" },
      { emoji: "🐟", name: "Peixe", speech: "Peixe" },
      { emoji: "🐠", name: "Peixe Tropical", speech: "Peixe Tropical" },
      { emoji: "🦐", name: "Camarão", speech: "Camarão" },
      { emoji: "🦑", name: "Lula", speech: "Lula" },
      { emoji: "🐙", name: "Polvo", speech: "Polvo" },
      { emoji: "🦀", name: "Caranguejo", speech: "Caranguejo" },
      { emoji: "🪸", name: "Coral", speech: "Coral" },
      { emoji: "🪼", name: "Água Viva", speech: "Água Viva" },
    ],
  },
  {
    id: "fruits",
    title: "Pomar das Frutas",
    color: "red", // var(--game-red)
    bgGradient: "from-red-100 to-pink-200",
    icon: "🍎",
    items: [
      { emoji: "🍎", name: "Maçã", speech: "Maçã" },
      { emoji: "🍐", name: "Pera", speech: "Pera" },
      { emoji: "🍊", name: "Laranja", speech: "Laranja" },
      { emoji: "🍋", name: "Limão", speech: "Limão" },
      { emoji: "🍌", name: "Banana", speech: "Banana" },
      { emoji: "🍉", name: "Melancia", speech: "Melancia" },
      { emoji: "🍇", name: "Uva", speech: "Uva" },
      { emoji: "🍓", name: "Morango", speech: "Morango" },
      { emoji: "🫐", name: "Mirtilo", speech: "Mirtilo" },
      { emoji: "🍒", name: "Cereja", speech: "Cereja" },
      { emoji: "🍍", name: "Abacaxi", speech: "Abacaxi" },
      { emoji: "🥭", name: "Manga", speech: "Manga" },
      { emoji: "🥝", name: "Kiwi", speech: "Kiwi" },
      { emoji: "🥥", name: "Coco", speech: "Coco" },
      { emoji: "🍑", name: "Pêssego", speech: "Pêssego" },
    ],
  },
  {
    id: "food",
    title: "Banquete Delicioso",
    color: "orange", // var(--game-orange)
    bgGradient: "from-orange-100 to-yellow-200",
    icon: "🍔",
    items: [
      { emoji: "🍔", name: "Hambúrguer", speech: "Hambúrguer" },
      { emoji: "🍟", name: "Batata Frita", speech: "Batata Frita" },
      { emoji: "🍕", name: "Pizza", speech: "Pizza" },
      { emoji: "🌭", name: "Cachorro-quente", speech: "Cachorro-quente" },
      { emoji: "🥪", name: "Sanduíche", speech: "Sanduíche" },
      { emoji: "🍝", name: "Macarrão", speech: "Macarrão" },
      { emoji: "🍰", name: "Bolo", speech: "Bolo" },
      { emoji: "🍪", name: "Biscoito", speech: "Biscoito" },
      { emoji: "🍫", name: "Chocolate", speech: "Chocolate" },
      { emoji: "🍿", name: "Pipoca", speech: "Pipoca" },
      { emoji: "☕", name: "Café", speech: "Café" },
      { emoji: "🥤", name: "Refrigerante", speech: "Refrigerante" },
    ],
  },
  {
    id: "shopping",
    title: "Hora das Compras",
    color: "purple", // var(--game-purple)
    bgGradient: "from-purple-100 to-violet-200",
    icon: "🛍️",
    items: [
      { emoji: "👕", name: "Camiseta", speech: "Camiseta" },
      { emoji: "👖", name: "Calça", speech: "Calça" },
      { emoji: "🧥", name: "Casaco", speech: "Casaco" },
      { emoji: "👗", name: "Vestido", speech: "Vestido" },
      { emoji: "👟", name: "Tênis", speech: "Tênis" },
      { emoji: "👞", name: "Sapato", speech: "Sapato" },
      { emoji: "🧢", name: "Chapéu", speech: "Chapéu" },
      { emoji: "🎒", name: "Mochila", speech: "Mochila" },
      { emoji: "👓", name: "Óculos", speech: "Óculos" },
      { emoji: "💍", name: "Anel", speech: "Anel" },
      { emoji: "👜", name: "Bolsa", speech: "Bolsa" },
      { emoji: "💄", name: "Batom", speech: "Batom" },
    ],
  },
  {
    id: "weather",
    title: "Clima e Tempo",
    color: "blue", // var(--game-blue)
    bgGradient: "from-sky-100 to-blue-200",
    icon: "☀️",
    items: [
      { emoji: "☀️", name: "Sol", speech: "Sol" },
      { emoji: "🌧️", name: "Chuva", speech: "Chuva" },
      { emoji: "⛈️", name: "Tempestade", speech: "Tempestade" },
      { emoji: "🌩️", name: "Raio", speech: "Raio" },
      { emoji: "🌪️", name: "Tornado", speech: "Tornado" },
      { emoji: "❄️", name: "Neve", speech: "Neve" },
      { emoji: "🌈", name: "Arco-íris", speech: "Arco-íris" },
    ],
  },
  {
    id: "city",
    title: "Cidade Movimentada",
    color: "gray", // Cor custom
    bgGradient: "from-gray-100 to-slate-200",
    icon: "🏙️",
    items: [
      { emoji: "🏠", name: "Casa", speech: "Casa" },
      { emoji: "🏢", name: "Prédio", speech: "Prédio" },
      { emoji: "🏥", name: "Hospital", speech: "Hospital" },
      { emoji: "🏫", name: "Escola", speech: "Escola" },
      { emoji: "🏦", name: "Banco", speech: "Banco" },
      { emoji: "🏭", name: "Fábrica", speech: "Fábrica" },
      { emoji: "🚏", name: "Ponto", speech: "Ponto de Ônibus" },
      { emoji: "🚇", name: "Metrô", speech: "Metrô" },
      { emoji: "🗑️", name: "Lixeira", speech: "Lixeira" },
    ],
  },
  {
    id: "vehicles",
    title: "Garagem Veloz",
    color: "red",
    bgGradient: "from-red-200 to-red-300",
    icon: "🚗",
    items: [
      { emoji: "🚗", name: "Carro", speech: "Carro" },
      { emoji: "🚌", name: "Ônibus", speech: "Ônibus" },
      { emoji: "🚑", name: "Ambulância", speech: "Ambulância" },
      { emoji: "🚒", name: "Bombeiros", speech: "Bombeiros" },
      { emoji: "🚓", name: "Polícia", speech: "Polícia" },
      { emoji: "🚚", name: "Caminhão", speech: "Caminhão" },
      { emoji: "🏍️", name: "Moto", speech: "Moto" },
      { emoji: "✈️", name: "Avião", speech: "Avião" },
      { emoji: "🚁", name: "Helicóptero", speech: "Helicóptero" },
      { emoji: "🚂", name: "Trem", speech: "Trem" },
      { emoji: "🚜", name: "Trator", speech: "Trator" },
    ],
  },
  {
    id: "music",
    title: "Sala de Música",
    color: "purple",
    bgGradient: "from-fuchsia-100 to-purple-200",
    icon: "🎸",
    items: [
      { emoji: "🎹", name: "Piano", speech: "Piano" },
      { emoji: "🎸", name: "Guitarra", speech: "Guitarra" },
      { emoji: "🥁", name: "Bateria", speech: "Bateria" },
      { emoji: "🎻", name: "Violino", speech: "Violino" },
      { emoji: "🎺", name: "Trompete", speech: "Trompete" },
      { emoji: "🎷", name: "Saxofone", speech: "Saxofone" },
      { emoji: "🎤", name: "Microfone", speech: "Microfone" },
      { emoji: "🎧", name: "Fones", speech: "Fones de Ouvido" },
      { emoji: "📻", name: "Rádio", speech: "Rádio" },
    ],
  },
];
