// =============================================
// ARQUIVO: src/js/achievements/achievementsData.js
// DESCRIÇÃO: Dados Estáticos de Todas as Conquistas
// =============================================

const achievementsList = [
  {
    id: 1,
    type: "played",
    gameId: 1,
    name: "Primeira: Formas",
    desc: "Comece a combinar a primeira forma.",
    icon: "🟡",
  },
  {
    id: 2,
    type: "played",
    gameId: 2,
    name: "Primeira: Som",
    desc: "Ouça e adivinhe o primeiro som.",
    icon: "👂",
  },
  {
    id: 3,
    type: "played",
    gameId: 3,
    name: "Primeira: Cor",
    desc: "Adivinhe sua primeira cor.",
    icon: "🎨",
  },
  {
    id: 4,
    type: "played",
    gameId: 4,
    name: "Primeira: Emoção",
    desc: "Reconheça a primeira emoção.",
    icon: "🙂",
  },
  {
    id: 5,
    type: "played",
    gameId: 5,
    name: "Primeira: Ligue os Pontos",
    desc: "Conecte seu primeiro par de pontos.",
    icon: "🔗",
  },
  {
    id: 6,
    type: "played",
    gameId: 6,
    name: "Primeira: Números",
    desc: "Faça seu primeiro pareamento de números.",
    icon: "🔢",
  },
  {
    id: 7,
    type: "played",
    gameId: 7,
    name: "Primeira: Sequência de Cores",
    desc: "Tente resolver a primeira sequência.",
    icon: "🟫",
  },
  {
    id: 8,
    type: "played",
    gameId: 8,
    name: "Primeira: Quebra-Cabeça",
    desc: "Encaixe sua primeira peça.",
    icon: "🧩",
  },
  {
    id: 9,
    type: "played",
    gameId: 9,
    name: "Primeira: Palavra",
    desc: "Acerte a primeira letra da palavra.",
    icon: "✍️",
  },
  {
    id: 10,
    type: "progress",
    gameId: 1,
    target: 12,
    name: "Mestre das Formas",
    desc: "Combine 12 formas (total de rodadas concluídas).",
    icon: "💎",
  },
  {
    id: 11,
    type: "progress",
    gameId: 2,
    target: 10,
    name: "Ouvido de Ouro",
    desc: "Acerte 10 sons na primeira tentativa.",
    icon: "🏆",
  },
  {
    id: 12,
    type: "progress",
    gameId: 3,
    target: 10,
    name: "Olho de Coruja",
    desc: "Acerte 10 cores na primeira tentativa.",
    icon: "👁️",
  },
  {
    id: 13,
    type: "progress",
    gameId: 4,
    target: 10,
    name: "Leitor Facial",
    desc: "Acerte 10 emoções na primeira tentativa.",
    icon: "🧠",
  },
  {
    id: 14,
    type: "progress",
    gameId: 5,
    target: 10,
    name: "Tecelão de Linhas",
    desc: "Complete 10 níveis do Ligue os Pontos.",
    icon: "🕸️",
  },
  {
    id: 15,
    type: "progress",
    gameId: 6,
    target: 10,
    name: "Mente Matemática",
    desc: "Acerte 10 sequências de números (pares conectados).",
    icon: "✨",
  },
  {
    id: 16,
    type: "progress",
    gameId: 7,
    target: 10,
    name: "Foco Inquebrável",
    desc: "Complete 10 níveis de Sequência de Cores (Linha 1 ou 2).",
    icon: "🎯",
  },
  {
    id: 17,
    type: "progress",
    gameId: 8,
    target: 10,
    name: "Quebra-Tudo",
    desc: "Finalize 10 quebra-cabeças (palavras completas).",
    icon: "🔨",
  },
  {
    id: 18,
    type: "progress",
    gameId: 9,
    target: 5,
    name: "Ortografia Inicial",
    desc: "Complete 5 palavras no Adivinhe a Palavra.",
    icon: "🖋️",
  },
  {
    id: 19,
    type: "consecutive",
    gameId: 2,
    target: 20,
    name: "Audição Perfeita",
    desc: "Acerte 20 sons **consecutivos** na primeira tentativa.",
    icon: "🎧",
  },
  {
    id: 20,
    type: "consecutive",
    gameId: 9,
    target: 3,
    name: "Sequência de Palavras",
    desc: "Complete 3 palavras **consecutivas**.",
    icon: "📜",
  },
  {
    id: 21,
    type: "mastery",
    category: "animals",
    target: 10,
    name: "Rei da Fazenda",
    desc: "Acerte 10 sons de animais diferentes na primeira tentativa.",
    icon: "🦁",
  },
  {
    id: 22,
    type: "mastery",
    category: "fruits",
    target: 10,
    name: "Cestinha de Frutas",
    desc: "Acerte 10 sons de frutas diferentes na primeira tentativa.",
    icon: "🍇",
  },
  {
    id: 23,
    type: "mastery",
    category: "diversos",
    target: 10,
    name: "Mundo dos Sons",
    desc: "Acerte 10 sons diversos diferentes na primeira tentativa.",
    icon: "🗺️",
  },
  {
    id: 25,
    type: "progress",
    gameId: 10,
    target: 10,
    name: "Primeira Dezena Auditiva",
    desc: "Acerte 10 sons no total.",
    icon: "🔟",
  },
  {
    id: 26,
    type: "progress",
    gameId: 10,
    target: 20,
    name: "Mente Sônica",
    desc: "Acerte 20 sons no total.",
    icon: "🎶",
  },

  {
    id: 27,
    type: "progress",
    gameId: 10,
    target: 5,
    name: "Viajante de Meio Percurso",
    desc: "Obtenha 5 Mapas de Jornada.",
    icon: "🗺️",
  },
  {
    id: 28,
    type: "progress",
    gameId: 10,
    target: 10,
    name: "Rei dos Mapas",
    desc: "Obtenha 10 Mapas de Jornada.",
    icon: "👑",
  },

  {
    id: 29,
    type: "skill",
    gameId: 10,
    target: 3,
    name: "Teimoso",
    desc: "Erre 3 vezes seguidas.",
    icon: "🤯",
    check: "checkWrongStreak",
  },
  {
    id: 30,
    type: "skill",
    gameId: 10,
    target: 10,
    name: "Na Mira",
    desc: "Acerte 10 vezes seguidas.",
    icon: "✅",
    check: "checkCorrectStreak",
  },

  {
    id: 31,
    type: "modes",
    gameId: 10,
    target: 1,
    name: "Aventureiro Livre",
    desc: "Jogue o Modo Livre pela primeira vez.",
    icon: "🎈",
    check: "checkFreeModePlayed",
  },

  {
    id: 32,
    type: "journey",
    gameId: 10,
    target: "wild_life",
    name: "Domador da Selva",
    desc: "Complete a jornada 'Floresta Selvagem'.",
    icon: "🦁",
  },
  {
    id: 33,
    type: "journey",
    gameId: 10,
    target: "farm",
    name: "Amigo do Campo",
    desc: "Complete a jornada 'Fazenda Feliz'.",
    icon: "🚜",
  },
  {
    id: 34,
    type: "journey",
    gameId: 10,
    target: "aquatic",
    name: "Explorador Submarino",
    desc: "Complete a jornada 'Mundo Aquático'.",
    icon: "🐬",
  },
  {
    id: 35,
    type: "journey",
    gameId: 10,
    target: "fruits",
    name: "Apanhador de Frutas",
    desc: "Complete a jornada 'Pomar das Frutas'.",
    icon: "🍎",
  },
  {
    id: 36,
    type: "journey",
    gameId: 10,
    target: "food",
    name: "Banquetista",
    desc: "Complete a jornada 'Banquete Delicioso'.",
    icon: "🍔",
  },
  {
    id: 37,
    type: "journey",
    gameId: 10,
    target: "shopping",
    name: "Elegância",
    desc: "Complete a jornada 'Hora das Compras'.",
    icon: "🛍️",
  },
  {
    id: 38,
    type: "journey",
    gameId: 10,
    target: "weather",
    name: "Caçador de Arco-Íris",
    desc: "Complete a jornada 'Clima e Tempo'.",
    icon: "🌈",
  },
  {
    id: 39,
    type: "journey",
    gameId: 10,
    target: "city",
    name: "Cidadão Ativo",
    desc: "Complete a jornada 'Cidade Movimentada'.",
    icon: "🏙️",
  },
  {
    id: 40,
    type: "journey",
    gameId: 10,
    target: "vehicles",
    name: "Mestre da Garagem",
    desc: "Complete a jornada 'Garagem Veloz'.",
    icon: "🚗",
  },
  {
    id: 41,
    type: "journey",
    gameId: 10,
    target: "music",
    name: "Maestro do Som",
    desc: "Complete a jornada 'Sala de Música'.",
    icon: "🎸",
  },

  {
    id: 42,
    type: "skill",
    gameId: 10,
    target: 1,
    name: "Desbravador de Sons",
    desc: "Complete todas as 10 jornadas disponíveis.",
    icon: "🗺️",
    check: "checkAllWorldsCompleted",
  },

  {
    id: 43,
    type: "bonus",
    gameId: 0,
    target: 20,
    name: "Estrela Suprema",
    desc: "Desbloqueie 20 conquistas principais.",
    icon: "🌟",
  },

  {
    id: 50,
    type: "skill",
    gameId: 4,
    target: 1,
    name: "Nova Descoberta",
    desc: "Desbloqueie uma emoção nova no álbum.",
    icon: "🧠",
    check: "checkEmotionCollection",
  },
  {
    id: 51,
    type: "skill",
    gameId: 4,
    target: 5,
    name: "Explorador de Sentimentos",
    desc: "Identifique 5 emoções diferentes.",
    icon: "🔮",
    check: "checkEmotionCollection",
  },
  {
    id: 52,
    type: "skill",
    gameId: 4,
    target: 10,
    name: "Mestre da Empatia",
    desc: "Identifique 10 emoções diferentes.",
    icon: "🎯",
    check: "checkEmotionCollection",
  },

  {
    id: 53,
    type: "journey",
    gameId: 4,
    target: "level_1_basic",
    name: "O Básico",
    desc: "Complete o Nível 1 (Emoções Básicas).",
    icon: "🥇",
  },
  {
    id: 54,
    type: "journey",
    gameId: 4,
    target: "level_2_social",
    name: "Socializando",
    desc: "Complete o Nível 2 (Emoções Sociais).",
    icon: "🥈",
  },
  {
    id: 55,
    type: "journey",
    gameId: 4,
    target: "level_3_complex",
    name: "Pensando Fundo",
    desc: "Complete o Nível 3 (Emoções Complexas).",
    icon: "🥉",
  },
  {
    id: 56,
    type: "journey",
    gameId: 4,
    target: "level_4_physical",
    name: "Corpo e Mente",
    desc: "Complete o Nível 4 (Emoções Físicas).",
    icon: "🏅",
  },
  {
    id: 57,
    type: "skill",
    gameId: 4,
    target: 1,
    name: "Guru das Emoções",
    desc: "Complete todos os níveis da jornada.",
    icon: "🎖️",
    check: "checkAllEmotionLevelsCompleted",
  },

  {
    id: 58,
    type: "skill",
    gameId: 4,
    target: 5,
    name: "Sequência Emocional",
    desc: "Acerte 5 emoções seguidas sem errar.",
    icon: "⭐",
    check: "checkEmotionStreak",
  },
];
